SCREEN_WIDTH = 1777
SCREEN_HEIGHT = 1000
SCREEN_TITLE = "Chronobio"

FARM_LENGTH = SCREEN_WIDTH * 0.3

SOUP_FACTORY_DISTANCE_FROM_CENTER = FARM_LENGTH
SOUP_FACTORY_WIDTH = FARM_LENGTH / 6

FIELD_OFFSET = FARM_LENGTH / 7 * 2
FIELD_WIDTH = FARM_LENGTH / 8
FIELD_DISTANCE = FARM_LENGTH / 7

FARM_BUILDING_DISTANCE_FROM_CENTER = FARM_LENGTH / 7
FARM_BUILDING_WIDTH = FARM_LENGTH / 7