[tool.black]
line-length = 88
include = '.pyi?$'
exclude = '''
/(
    .git
  | .hg
  | .mypy_cache
  | .tox
  | .venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[flake8]
max-line-length = 88
max-complexity = 10
